<?php
// $Id: emfield.install,v 1.1.6.8 2008/07/25 11:45:51 alexua Exp $

/**
 * @file
 * This is the emfield.module's install, configuration, and removal file.
 */

/**
 * Implementation of hook_install().
 */
function emfield_install() {
}

/**
 * Implementation of hook_uninstall().
 */
function emfield_uninstall() {
}

/**
 * Implementation of hook_enable().
 */
function emfield_enable() {
}

/**
 * Implementation of hook_disable().
 */
function emfield_disable() {
}
